config/routes.rb
Shopnochura::Application.routes.draw do
  

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "oauths/oauth"

  get "oauths/callback"

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "sessions/new"

  get "users/new"

  get "signup-login" => "users#signup_login", :as => "signup_login"

  root :to => 'public#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :companies do
    resources :reviews, except: [:index, :show]
  end  

  get "signup" => "users#new", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users do
    member do
      get :activate
    end
  end

  resources :reviews
  
  resources :sessions

  resources :password_resets

   root :to => 'public#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  has_many :reviews




  validates_length_of :password, :minimum => 6, :message => "password must be at least 6 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  validates :email, :uniqueness => true

  validates :email, :presence => true




  # def self.authenticate_regardless_of_activation_state(*credentials)
  #   raise ArgumentError, "at least 2 arguments required" if credentials.size < 2
  #   credentials[0].downcase! if @sorcery_config.downcase_username_before_authenticating
  #   user = find_by_credentials(credentials)

  #   set_encryption_attributes()

  #   _salt = user.send(@sorcery_config.salt_attribute_name) if user && !@sorcery_config.salt_attribute_name.nil? && !@sorcery_config.encryption_provider.nil?
  #   user if user && credentials_match?(user.send(@sorcery_config.crypted_password_attribute_name),credentials[1],_salt)
  # end

  def self.authenticate_regardless_of_activation_state(*credentials)
	  prevent_check = self.sorcery_config.before_authenticate.delete(:prevent_non_active_login)
	  user = self.authenticate(*credentials)
	  self.sorcery_config.before_authenticate << prevent_check if prevent_check
	  return user
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login, :only => [:new, :create, :activate]

	def activate
	  if (@user = User.load_from_activation_token(params[:id]))
	    @user.activate!
	    redirect_to(login_path, :notice => 'User was successfully activated.')
	  else
	    not_authenticated
	  end
	end

	def new
		@user = User.new
	end	

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, :notice => "Signed Up!"
		else
			render :new
		end	
	end

	def signup_login
		@user = User.new
	end


  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => "form-horizontal", :role => "form", :method => :post}  do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h4>Please correct the error(s) below:</h4>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :email, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :email, :placeholder => "Email Address", 
      :class => 'form-control', :required => true, :autocomplete => "off" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.password_field :password, :placeholder => "Password", 
      :class => 'form-control', :required => true, :autocomplete => "off" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.password_field :password_confirmation, :placeholder => "Retype Password", 
      :class => 'form-control', :required => true, :autocomplete => "off" %>
    </div>
  </div>


  <!-- <div class="notice">
    By clicking "Sign up" you confirm that you accept the
    <%= link_to "Terms of Service", "javascript:void(0)", :target => "_blank" %>
    and
    <%= link_to "Privacy Policy", "javascript:void(0)", :target => "_blank" %>
  </div> -->


  


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= submit_tag "Sign up", :class => 'btn btn-success' %>
    </div>
  </div>



<% end %>

app/views/users/new.html.erb
<div class="shopno-theme low-paded">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/signup_login.html.erb
<div class="col-md-12">
	<div class="row shopno-theme">
		<div class="col-md-5">
			<h4 style="border-bottom: 1px solid #ccc;padding-bottom: 10px; margin-bottom: 20px;">Login</h4>
			<%= render "sessions/form" %>
		</div>
		<div class="col-md-1 text-center" style="margin: 100px 0;font-weight: bold; color: #ec790d">
			-- OR --
		</div>
		<div class="col-md-6">
			<h4 style="border-bottom: 1px solid #ccc;padding-bottom: 10px; margin-bottom: 12px;">Sign Up</h4>
			<%= render 'form' %>
		</div>	
	</div>
</div>
<%= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %>