config/routes.rb
Shopnochura::Application.routes.draw do
  

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "oauths/oauth"

  get "oauths/callback"

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "sessions/new"

  get "users/new"

  get "signup-login" => "users#signup_login", :as => "signup_login"

  root :to => 'public#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :companies do
    resources :reviews, except: [:index, :show]
  end  

  get "signup" => "users#new", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users do
    member do
      get :activate
    end
  end

  resources :reviews
  
  resources :sessions

  resources :password_resets

   root :to => 'public#home'

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :title

  has_many :reviews

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  before_filter :require_login, :only => [:new, :create]

  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  def show
  	@company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(params[:company])
    if @company.save
      flash[:notice] = "Congrets. Now write down the review of your company"
      redirect_to new_company_review_path(@company)
    else
      render :new
    end 

  end  



  
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/index.html.erb
<!-- <h1>Listing companies</h1> -->

<div class="page-header" style="border-bottom: none;">
  <h1><small>Companies</small></h1>
</div>


<table class="table table-hover">
  <tr>
    <td>Title</td>
    <td>Address</td>
    <td></td>
  </tr>

<% @companies.each do |company| %>
  
    <tr>
      
      <td>
        <%= link_to company_path(company), :class => "invisible-link" do %>
            <%= company.title %>
        <% end %>    
      </td>
      
      <td>
        <%= link_to company_path(company), :class => "invisible-link" do %>
          <%= company.address %>
        <% end %>
      </td>

      <td>
        <%= link_to "Write a review", new_company_review_path(company), :class => "btn btn-success"  %>
      </td>

    </tr>
   
<% end %>
<tr>
      
      <td>
        
      </td>
      
      <td class="text-right" style="color: #27338a; font-style: italic;">
        Your company is not available on the list
      </td>

      <td>
        <%= link_to "Write a review here", new_company_path, :class => "btn btn-warning", :type => "button" %>
      </td>

    </tr>

</table>

<br />

app/views/companies/new.html.erb
<div class="row shopno-theme">
	<%= form_for @company, :html => {:class => "form-horizontal", :role => "form"}  do |f| %>
		<% if @company.errors.any? %>
		    <div class="error_messages">
		      <h4>Please correct the error(s) below:</h4>
		      <ul>
		        <% for message in @company.errors.full_messages %>
		          <li><%= message %></li>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <div class="form-group">
		    <%= f.label :title, "Name", :class => "col-lg-2 control-label" %>
		    <div class="col-lg-10">
		      <%= f.text_field :title, :placeholder => "Company Name", 
		      :class => 'form-control', :required => true %>
		    </div>
		  </div>

		  <div class="form-group">
		    <%= f.label :address, "Address", :class => "col-lg-2 control-label" %>
		    <div class="col-lg-10">
		      <%= f.text_area :address, :placeholder => "Company Address", 
		      :class => 'form-control', :required => true, :rows => "4" %>
		    </div>
		  </div>

		  <div class="form-group">
		    <div class="col-lg-offset-2 col-lg-10">
		      <%= submit_tag "Submit and write review of your company", :class => 'btn btn-success' %>
		    </div>
		  </div>


	<% end %>
</div>

app/views/companies/show.html.erb
<div class="page-header" style="border-bottom: none;">
  <h1><small><%= @company.title %></small></h1>
</div>

<address>
  <%= @company.address %>
</address>