config/routes.rb
Shopnochura::Application.routes.draw do
  

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "oauths/oauth"

  get "oauths/callback"

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "sessions/new"

  get "users/new"

  get "signup-login" => "users#signup_login", :as => "signup_login"

  root :to => 'public#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :companies do
    resources :reviews, except: [:index, :show]
  end  

  get "signup" => "users#new", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users do
    member do
      get :activate
    end
  end

  resources :reviews
  
  resources :sessions

  resources :password_resets

   root :to => 'public#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :title

  has_many :reviews

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :company_id, :content, :title, :user_id,
  :positive_sides, :negative_sides

  belongs_to :user
  belongs_to :company 


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  has_many :reviews




  validates_length_of :password, :minimum => 6, :message => "password must be at least 6 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  validates :email, :uniqueness => true

  validates :email, :presence => true




  # def self.authenticate_regardless_of_activation_state(*credentials)
  #   raise ArgumentError, "at least 2 arguments required" if credentials.size < 2
  #   credentials[0].downcase! if @sorcery_config.downcase_username_before_authenticating
  #   user = find_by_credentials(credentials)

  #   set_encryption_attributes()

  #   _salt = user.send(@sorcery_config.salt_attribute_name) if user && !@sorcery_config.salt_attribute_name.nil? && !@sorcery_config.encryption_provider.nil?
  #   user if user && credentials_match?(user.send(@sorcery_config.crypted_password_attribute_name),credentials[1],_salt)
  # end

  def self.authenticate_regardless_of_activation_state(*credentials)
	  prevent_check = self.sorcery_config.before_authenticate.delete(:prevent_non_active_login)
	  user = self.authenticate(*credentials)
	  self.sorcery_config.before_authenticate << prevent_check if prevent_check
	  return user
  end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  before_filter :require_login, :only => [:new, :create]

  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  def show
  	@company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(params[:company])
    if @company.save
      flash[:notice] = "Congrets. Now write down the review of your company"
      redirect_to new_company_review_path(@company)
    else
      render :new
    end 

  end  



  
end

app/controllers/oauths_controller.rb
# app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_filter :require_login
      
  # sends the user on a trip to the provider,
  # and after authorizing there back to the callback url.
  def oauth
    login_at(params[:provider])
  end
      
  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end
  
  #example for Rails 4: add private method below and use "auth_params[:provider]" in place of 
  #"params[:provider] above.

  # private
  # def auth_params
  #   params.permit(:code, :provider)
  # end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
  	fetch = FetchJobs.new
  	@reviews = Review.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  
  def new
    @company = Company.find(params[:company_id]) if params[:company_id]
    @review = @company.present? ? @company.reviews.build : Review.new
  end

  def create
    @review = current_user.reviews.new(params[:review])
    @review.company_id = params[:company_id]
    if @review.save
      flash[:notice] = "Review saved"
    else
      render :new
    end  
  end

  def edit
  end

  def update
  end

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end


  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  
  # def create
  #   puts "====================got it !!!!!!============================="
  #   respond_to do |format|
  #     if @user = login(params[:email],params[:password])
  #       format.html { redirect_back_or_to(root_path, :notice => 'Login successful.') }
  #       format.xml { render :xml => @user, :status => :created, :location => @user }
  #     else
  #       format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
  #       format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end


  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in"
    else
      user = User.authenticate_regardless_of_activation_state params[:email], params[:password]
      if user && user.activation_state == 'pending'
        auto_login(user)
        puts "i got here  :)============================================="
        redirect_back_or_to root_url, :notice => "Logged in. But, check ur email address to activate ur account."
      else
        flash.now.alert = "Email or password was invalid"
        render :new
      end
    end
  end






    
  def destroy
    logout
    redirect_to(root_path, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login, :only => [:new, :create, :activate]

	def activate
	  if (@user = User.load_from_activation_token(params[:id]))
	    @user.activate!
	    redirect_to(login_path, :notice => 'User was successfully activated.')
	  else
	    not_authenticated
	  end
	end

	def new
		@user = User.new
	end	

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, :notice => "Signed Up!"
		else
			render :new
		end	
	end

	def signup_login
		@user = User.new
	end


  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>ShopnoChura</title>
    <%= csrf_meta_tags %>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag    "application",  :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <%= javascript_include_tag "ie" %>
    <![endif]-->

    <link href='http://fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

</head>
<body>
  <!--[if lt IE 7]>
      <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
<header id="page-header">
  <div class="top-bar">
    <div class="container head-portion">
        <div class = "row">
          <div class="col-xs-12 col-sm-6 col-md-6">
            <%= link_to image_tag("logo.png"), root_path %>      
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <ul class="nav nav-pills top-navigation">
              <li class="active"><a href="#">Home</a></li>
              <% if current_user %>
                <li><%= link_to "Log out", logout_path %></li>
              <% else %>
                <li><%= link_to "Sign Up", signup_path %></li>
                <li><%= link_to "Log In", login_path %></li> 
              <% end %>
            </ul>
          </div>  
         </div> 
    </div>
  </div>

  
  
</header>

<div id="page-content">
  <div class="container">
    
    <!-- <div style="min-height: 36px;"> -->
    <% if flash.present? %>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: name %>
          <% end -%>
        </div>
      <% end %>
    <!-- </div> -->
    <div class="inner-container">
      <div class="row right-small-margin">
        <%= yield %>
    </div><!--/row right-small-margin-->
    </div><!--/inner-container-->
  </div><!--/container-->
</div> <!--/#page-content-->
<!-- <div style="display:inline-block; width: 56px; height: 81px; position: fixed; bottom: 0px; right: 0px">
  <%= image_tag "landing-leaves.png", :style => "width: 100%;" %> -->

</div>


</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>ShopnoChura</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag    "application",  :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <%= javascript_include_tag "ie" %>
    <![endif]-->

    <link href='http://fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

</head>
<body>
  <!--[if lt IE 7]>
      <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
<header id="page-header">
  <div class="top-bar">
    <div class="container head-portion">
        <div class = "row">
          <div class="col-xs-12 col-sm-6 col-md-6">
            <%= link_to image_tag("logo.png"), root_path %>      
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <ul class="nav nav-pills top-navigation">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">Profile</a></li>
              <li><a href="#">Messages</a></li>
            </ul>
          </div>  
         </div> 
    </div>
  </div>

  
  
</header>

<div id="page-content">
  <div class="container">
    <div class="inner-container">

      


      <%= yield %>





    </div><!--/inner-container-->
  </div><!--/container-->
</div> <!--/#page-content-->



</body>
</html>